# Generated by Django 2.2.4 on 2019-08-25 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_noticias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticias',
            new_name='Noticia',
        ),
    ]
